name: configure
description: A config management library.
version: 0.1.0
publish_to: 'none'

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  version:
    git:
      url: https://github.com/YDITS/YDITS-SSC.git
      path: packages/version
      ref: master

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
