include: package:flutter_lints/flutter.yaml

linter:
  rules:
    - always_declare_return_types
    - always_put_required_named_parameters_first
    - always_specify_types
    - annotate_overrides
    - cancel_subscriptions
    - eol_at_end_of_file
    - prefer_const_constructors
    - unawaited_futures
