name: api_localhost_proxy
description: "A Flutter package that APIs localhost proxy server."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  logging: ^1.3.0
  version:
    path: ../version
  configure:
    path: ../configure

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
